### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by patte** [orbiting/app#1]
- [x] setup react-native (also see offline support in #6, but don't be blocked by it)
- [x] The App must be available on iOS (9.0+) and Android (4.4+).
  - These min. version requirements are up for discussion if the app developer sees big advantages in raising them.
  - On iOS we prefer Swift over Objective-C.
- [x] Developer Accounts

**Comment by diegomura** [comment]
This project is created using [Expo](https://docs.expo.io/versions/latest/). Expo apps are regular react-native apps, but that additionally implements many (fully-tested) handy components and device API wrappers that react native does not have from out of the box. Many of which will be handy particularly for this project, such as [AuthSession](https://docs.expo.io/versions/latest/sdk/auth-session), cross-os [push notifications](https://docs.expo.io/versions/v27.0.0/guides/push-notifications#__next), a more [straightforward publishing process](https://docs.expo.io/versions/v27.0.0/workflow/how-expo-works#publishingdeploying-an-expo-app-in-production) and the ability to share and test the app [before deploying to the stores](https://docs.expo.io/versions/v27.0.0/workflow/publishing#how-to-publish). [CRNA](https://github.com/react-community/create-react-native-app) uses expo under the hood. They are almost the same thing

It's important to mention that since it's just a regular react-native app, we can always [eject](https://github.com/react-community/create-react-native-app#npm-run-eject) and have real access to the native code. However, if not needed it's usually recommended not to do it.

About Android and iOS versions, Expo apps supports [Android 4.4+ and iOS 9+](https://docs.expo.io/versions/v27.0.0/introduction/faq#what-version-of-android-and-ios-are)

Since the app will be just WebViews, offline support is something I will have to see in detail in the future. If we were showing articles natively (by querying the API and getting the article JSON and so on) offline support would be a bit simpler, since we can cache that data.

**Comment by tpreusse** [comment]
Expo is not for us. It relies on a proprietary backend. The handy wrappers are possible because they all connect to their (backend) services. All of our apps need to be fully open source, including the backend that powers them. Expo seems super careful to hide that and does not have a business model yet—makes one wonder what they are up to.

WalmartLabs published an [open source OTA thing called «Electrode Over The Air»](https://medium.com/walmartlabs/publish-react-native-bundles-over-the-air-with-the-first-electrode-rn-release-3780edb387ba). Maybe we could use that? But also research other alternatives without any cloud or backend lock-ins, if there are. For notifications we'll either implement the complete backend ourselves—talking to Google and Apple—or use a completely open source abstraction that we can run on server that we control. One of our backend engineers would take care of the server implementation but please suggest good options and define what kind of APIs you'd need on the app side.

**Comment by diegomura** [comment]
Thanks for your response!

What you say makes sense. I didn't know that the backend side wasn't open-source, but Expo business model was always a big question mark for me, even though they say in their site they will never charge for using it (they don't specifically mention any of their services though).

The same arguments apply for CRNA? As I said, they are basically the "same", but you can choose not to use their backend services (for notifications for ex.) but use all the great components and API wrappers builded on top of it.

Otherwise, I would initially be biased to use "plain" react-native, developing or using the open-source plugins we need. This will also give us more flexibility. I'll read carefully about Electrode tonight (didn't know that product) and research if there are similar ones and keep the discussion open.

The code I uploaded is just the project skeleton, nothing more. Will erase it asap

**Comment by tpreusse** [comment]
As far as I understand CRNA just scaffolds a expo app. We can use all open source code as long as it permits to point it at a different backend and the needed backend is documented and it's feasible to implement such a backend on our side.

From a really high level perspective the ideal would be that a app is a full featured `republik-frontend`. But we don't want to re-implement everything and maintain two code bases. Therefore the easy solution is to use a web view, possibly with some hooks/side communication channels into the `react-native` runtime, at least for proper native notifications. It might be possible to make this web view work offline with service workers or a custom solution. The web uses [`apollo-cache-inmemory`](https://github.com/orbiting/republik-frontend/blob/master/lib/apollo/initApollo.js) this could potentially be hooked into and e.g. saved to disk (with TTLs).

Another approach would be to load the next.js code bundles from the deployed `republik-frontend` in a «OTA manner». And run the whole thing on the phone—do `react-dom` rendering on the phone (probably in a webview to but with js resources loaded locally instead of the cdn). A tested build task to build app specific bundles could be added to `republik-frontend`, if necessary and helpful. Not sure if there is any prior art of doing this with `next.js`.

**Comment by diegomura** [comment]
I just pushed what I think can be the starting point of the app. 
It consist on a basic `react-native init` app, with the CodePush and PushNotifications setup (only for ios for the moment. Will test it on Android today), plus a dummy app icon, and some logic to test the OTA update.
