### ISSUE TITLE
Show frontend page transition loader on app

### ISSUE THREAD

**Issue by diegomura** [orbiting/app#105]

**Comment by tpreusse** [comment]
Can you add screenshots of this case. I saw something similar, maybe the same thing. But I have to think about it some more.

**Comment by diegomura** [comment]
Of course. I'll add some today

**Comment by patte** [comment]
It's impossible to make a screenshot, but I can reproduce what diego was saying.
- Go to "Rubriken" and reload the page
- make sure the SubNav is visible
- tip on "Magazin"
- now quickly scroll up a little, you'll see the loading bar was present under the SubNav and is loading, but it was not visible with the SubNav expanded.
On the desktop this problem doesn't exist because the loading bar is at the very top and the subnav doesn't get in the way
Can you have a look at this @tpreusse?
