### ISSUE TITLE
mind the notch

### ISSUE THREAD

**Issue by patte** [orbiting/app#140]
When the gallery is open, the `x/y` and close action overlap the clock and battery on the iPhone X.

![image from ios 2](https://user-images.githubusercontent.com/3500621/43914780-0e724348-9c09-11e8-98fc-abf19c2ca65d.jpg)

**Comment by diegomura** [comment]
Some conclusions:

- It is possible _in theory_ to edit status bar with the react-native [StatusBar](https://facebook.github.io/react-native/docs/statusbar) component. However, I couldn't make the `backgroundColor` work. I think it might be because react-navigator. They have a [guide](https://reactnavigation.org/docs/en/status-bar.html) about how to style the status bar, but using the stacknavigator the only way seems to be to remove the header at all (`headerMode: 'none'`). It is possible to make fonts white, by switching between `light-content` and  `dark-content`. So my first point would be possible. Second point not that much.

- There is another possible way: hidding the status bar when gallery open. I implemented this and I liked the results. It's like a full screen gallery. this is how it looks on ios:

![kapture 2018-08-09 at 15 53 25](https://user-images.githubusercontent.com/5600341/43919473-606e97f4-9bec-11e8-9c6d-de8cf10bd796.gif)

**Comment by patte** [comment]
I also like the solution: real fullscreen. On the iPhone X it's working well. On android I get a wired orange border around everything, when in the new fullscreen. I never saw that before.
![screenshot_2018-08-09-21-08-06](https://user-images.githubusercontent.com/3500621/43920268-b736a51e-9c18-11e8-8058-0aabea769f8d.png)

**Comment by diegomura** [comment]
Haha damn it apple. That's only fixable from the frontend, just adding some extra margin in the items. if we add it app-side, the footer will also have it, and the result would be weird

**Comment by patte** [comment]
Let's talk about landscape here: https://github.com/orbiting/app/issues/144
