### ISSUE TITLE
Permanent warning if GSF is not installed

### ISSUE THREAD

**Issue by micressor** [orbiting/app#163]
## Bug Report

Unfortunately I get the error message every time that the framework is not installed. I am aware of this, but the app works for my needs. 

**Steps to Reproduce**

Do not use the app for a longer period of time. So that it is removed from memory.

**Actual Results**

![screenshot_republik_20180923-090516_1](https://user-images.githubusercontent.com/131317/46226482-b839bf80-c35c-11e8-9ee4-9e8f1206c8a9.png)

**Expected Results**
It should be possible to disable this message.

**Environment**

- LineageOS 15.1 (Android 8.1.0) without GSF
- App Version: 1.0.2

**Comment by tpreusse** [comment]
Thank you for reporting.

We're looking into ways to suppress this error and replace it with a custom, one time or one time per version, message.

We only use GSF for notifications via Google Firebase as far as I am aware. Am I right to assume notifications do not work on your device and you do not mind?

**Comment by micressor** [comment]
Exactly, I haven't received any notifications yet.

Also the registration via app (instead of email) doesn't work, which might have something to do with the notifications.

**Comment by tpreusse** [comment]
Yeah that only gets activated once a APN (Apple) or Firebase (Android) token is registered in our backend.

It would technically work without the notification but you'd have to open the app without getting a notification asking you to do so on your lock screen / in the notification center. Maybe we'll add a way to manually activate it when one comes along with a device without GSF.

Do notifications in other third party apps work? Do you know what notification setup they use? A direct background connection per app or another, more open, notification provider instead of [GCM/FCM](https://developers.google.com/cloud-messaging/)?

**Comment by micressor** [comment]
I have opened a separate issue #166 for the notification topic.

**Comment by zukunft** [comment]
On lineage OS 20 (Android 13) the app does not start at all. Should I create a new issue for this?

**Comment by ovbm** [comment]
Thanks for the report. 
Does the web app work when added to the home screen?

**Comment by zukunft** [comment]
Thanks for the fast answer. No, it alos does not start from the home screen. Here some parts from the log:

02-24 18:06:14.968  1631  9194 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=app.republik/.MainActivity bnds=[849,551][1055,920]} from uid 10134

...
02-24 18:06:15.034 20683 20683 W ComponentDiscovery: Class com.google.firebase.dynamicloading.DynamicLoadingRegistrar is not an found.
02-24 18:06:15.035 20683 20683 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 10179; state: DISABLED
02-24 18:06:15.036 20683 20683 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
02-24 18:06:15.040 20683 20683 I FirebaseInitProvider: FirebaseApp initialization successful
02-24 18:06:15.042 20683 20707 E FirebaseInstanceId: Google Play services missing or without correct permission.
02-24 18:06:15.044 20683 20683 D SoLoader: libjscexecutor.so not found on /data/app/~~KXZISWyMJ5k_9q3Wqm9XhQ==/app.republik-XqXSzdeC8RsdY2sjXP0yMg==/lib/arm64
02-24 18:06:15.044 20683 20683 D SoLoader: libjscexecutor.so not found on null
02-24 18:06:15.045 20683 20683 D SoLoader: libjscexecutor.so not found on /system/lib64
02-24 18:06:15.045 20683 20683 D SoLoader: libjscexecutor.so not found on /vendor/lib64
02-24 18:06:15.045 20683 20683 E SoLoader: couldn't find DSO to load: libjscexecutor.so
...
02-24 18:06:15.046 20683 20683 D AndroidRuntime: Shutting down VM
--------- beginning of crash
02-24 18:06:15.046 20683 20683 E AndroidRuntime: FATAL EXCEPTION: main
02-24 18:06:15.046 20683 20683 E AndroidRuntime: Process: app.republik, PID: 20683
02-24 18:06:15.046 20683 20683 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~KXZISWyMJ5k_9q3Wqm9XhQ==/app.republik-XqXSzdeC8RsdY2sjXP0yMg==/lib/arm64 flags = 0]
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = null]
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	Native lib dir: /data/app/~~KXZISWyMJ5k_9q3Wqm9XhQ==/app.republik-XqXSzdeC8RsdY2sjXP0yMg==/lib/arm64
02-24 18:06:15.046 20683 20683 E AndroidRuntime:  result: 0
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:25)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:19)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:23)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:394)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:344)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at app.republik.MainApplication.onCreate(MainApplication.java:61)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-24 18:06:15.046 20683 20683 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
02-24 18:06:15.048  1631 20708 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-24 18:06:15.048  1631  9194 W ActivityTaskManager:   Force finishing activity app.republik/.MainActivity
02-24 18:06:15.061 20683 20683 I Process : Sending signal. PID: 20683 SIG: 9
02-24 18:06:15.073  1631  9196 I ActivityManager: Process app.republik (pid 20683) has died: fg  TOP 
02-24 18:06:15.073   861   861 I Zygote  : Process 20683 exited due to signal 9 (Killed)
02-24 18:06:15.074  1631  1773 I libprocessgroup: Successfully killed process cgroup uid 10179 pid 20683 in 0ms


I can provide more details if needed.

**Comment by zukunft** [comment]
I updated the app to v2.2.3 / 278 and now the app starts on lineageOS 20.0 (from 25.April 2023) without Play Store.
