### ISSUE TITLE
App crashes when not used for some time in iOS

### ISSUE THREAD

**Issue by jstudach** [orbiting/app#168]
## Bug Report

When the iOS-App is running, but not used for some time, it shows only a blank screen. Can be fixed by quitting and restarting the app.

**Steps to Reproduce**

^

**Actual Results**

will upload a screenshot next time it happens

**Expected Results**

**Environment**

iOS 12.0
1.0.1

**Possible Solutions**

**Comment by garamond** [comment]
Can't reproduce this. Let's put it on the backlog and wait for more reports.

**Comment by lwihler** [comment]
More problems concerning this:

> Jetzt gerade und zwischendurch funktioniert gar nichts auf der R App. Wissen Sie um das Problem und wenn ja, gedenken Sie es demnächst zu beheben? Ich probiere mit meinem iPhone erfolglos auf die App zuzugreifen.

>Der Zugriff via App auf dem Ipad funktioniert seit ein paar Tagen nur einmal. Bei einem späteren Zugriff kommt nur noch eine weisse Seite. Ich muss das IPad wieder neu starten. Die anderen Apps funktionieren einwandfrei. 
https://admin.republik.ch/users/cee18ba7-56e5-486a-aaa5-57a099d12c14

**Comment by tpreusse** [comment]
Most likely cause: the web content process can terminate to save memory. This probably happens when the app is backgrounded and not used.

There is a callback for this:
https://github.com/Telerik-Verified-Plugins/WKWebView/issues/41#issuecomment-172696256
> - (void)webViewWebContentProcessDidTerminate:(WKWebView *)webView

Our web view just logs this. Probably should remember and then re-init on app launch.

Logging:
https://github.com/CRAlpha/react-native-wkwebview/blob/750f5a701e01b5262278f04693cb7ddf90fb8fe1/ios/RCTWKWebView/CRAWKWebView.m#L609

**Comment by tpreusse** [comment]
A report of similar crashes and ways to detect it by an Firefox for iOS Engineer:
https://stackoverflow.com/questions/31994919/how-to-determine-why-wkwebview-is-crashing

**Comment by tpreusse** [comment]
PR to add callback to the JS wrapper:
https://github.com/CRAlpha/react-native-wkwebview/pull/218
