### ISSUE TITLE
Redirect deep linking to (external) URL leads to blank page

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/app#194]
## Bug Report

Scanning a QR code with a redirect URL ("short URL") opens app and renders a blank screen in app. 

This is true for non-Republik domains or specific, in-app excluded pages like offers if user is logged in. If user is not logged in, in-app excluded pages will be openend in browser.

**Steps to Reproduce**

1. Scan a QR code - or add them to notebook and click on it - containing a redirect to an (external) URL

![image](https://user-images.githubusercontent.com/331800/58699093-fe886800-839c-11e9-86e4-eb42d70c201e.png)

https://www.republik.ch/z/preispod
forwards to https://anchor.fm/republik-magazin/

![image](https://user-images.githubusercontent.com/331800/58699129-0fd17480-839d-11e9-8601-277047604956.png)

https://www.republik.ch/z/a1
forwards to https://www.republik.ch/angebote

**Actual Results**

Shows a blank screen in Republik-App on iOS.

**Expected Results**

Opens browser window with URL redirect is forwarding a user to.

**Environment**

- OS: iOS 12.2
- App Version: 1.1.1

**Comment by tpreusse** [comment]
Good catch!

Fixed with
https://github.com/orbiting/republik-frontend/commit/309d1b49a2cf281850a78c4b2dc837061a3fe138 & https://github.com/orbiting/republik-frontend/commit/c5ee635211d513d839f624bdd7ccadc0ae34dc3a

Directly putting the destinations URLs into the QR-Code would be faster and not lead to a weird jump into and out of the app.
