### ISSUE TITLE
Review sharing buttons

### ISSUE THREAD

**Issue by diegomura** [orbiting/app#71]
From internal testing:

> If I'd like to share an article, I'd probably do that after finishing it. So that's when I need to see the navigation bar. Currently I only see it when scrolling down and not when on the bottom. I have to scroll up a bit in order to make it appear (Android 6.0.1, Fairphone2, App-Version 0.0.7)

**Comment by diegomura** [comment]
@patte @tpreusse This is more of a design issue. This happens mostly because on the app, we hide webview buttons, and we show share icons when user scrolls,dissapearing when user arrives to the bottom of the page. Different fixes:

- Show share icon on webview, and trigger native dialog when clicked. I don't think this will fix completely the issue, but at least will be in the same way as the webpage
- Not hide share buttons when user arrives to the bottom of the page.

**Comment by patte** [comment]
on-hold until we have the design for the new nav-bar

**Comment by patte** [comment]
@diegomura We should show the action bar in the article, same as it is in the web. Less of a problem, because we also have the generic share icon in the web version.
This makes it easier for users to find the feature at the learned place. Speaking for itself, the icons should trigger the native-share/-pdf/-discussion behavior. I would show all icons, including download (which should take me to safari).
